### ISSUE TITLE
mac-x64.zip is broken

### ISSUE THREAD

**Issue by apivovarov** [SEVA77/circuitjs1#10]
Can not unzip `mac-x64.zip` 1.2.1 downloaded from [Release page](https://github.com/SEVA77/circuitjs1/releases)
```
unzip mac-x64.zip
echo $?
81
```

**Comment by apivovarov** [comment]
ok, I need to use `7z x mac-x64.zip`. Kurva ebana.

**Comment by SEVA77** [comment]
I've updated all the zip-files in the latest version.

Sorry for this ...

Hotya net. Idi nahuj.
