### ISSUE TITLE
Подскажите как создать отдельный блок схемы

### ISSUE THREAD

**Issue by MrakLula** [SEVA77/circuitjs1#13]
Не полчуается в последней версии создать отдельный блок схемы, какие бы выходы выходы не ставил - выдает ошибку, не знаю что делать.

**Comment by SEVA77** [comment]
Нужен "Маркированый узел" (Выходы и инф. элементы). Как-нибудь потом уточню это в переводе на русский.

**Comment by MrakLula** [comment]
Большое вам спасибо)
