### ISSUE TITLE
Audio Input not working

### ISSUE THREAD

**Issue by Arpeman** [SEVA77/circuitjs1#16]
Audio input doesn't give any voltage or amps
I have had old version ones that that worked just fine but can't find it anymore

I'm not good at coding so can't find more information than this about the issue

![Nimetön](https://github.com/SEVA77/circuitjs1/assets/67929532/e57e3dec-6a4e-482b-a88d-9a1468ab6234)

**Comment by SEVA77** [comment]
I checked the audio input. It just doesn't work. I know how to fix it but it will not be soon.

**Comment by SEVA77** [comment]
Now it works. Please check the new version.
