### ISSUE TITLE
Sidecar is overlaying the circuit...

### ISSUE THREAD

**Issue by ulrichloose** [SEVA77/circuitjs1#19]
You often need the sidebar to operate e.g. sliders. However, there is an error in the form that the displayed sidebar overlays the display area and the display area is not reduced by the size of the sidebar. This also covers the values display at the bottom right and that is really annoying. At the first start with the oscillating circuit, the program behaves flawlessly, but with new circuits or loaded circuits the error always occurs. Maybe this misconduct could be corrected?

**Comment by SEVA77** [comment]
I agree. The overlaying sidebar seemed like a good idea for me but I came to the same conclusion on the basis of my experience of using it and I'll try to fix it.

**Comment by SEVA77** [comment]
Perhaps I managed to fix everything you described. Please check the new version.

**Comment by SEVA77** [comment]
You're welcome!
