### ISSUE TITLE
Win packaging tool deprecated - what's next?

### ISSUE THREAD

**Issue by E3V3A** [SEVA77/circuitjs1#3]
This is a really great project! I wish I had seen it before.

Just to say something here...
I just noticed that the packaging tool you use has been deprecated (no longer maintained) for some time. So what other options do we have? 

* https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps

**Comment by CEBA77** [comment]
Hello. I see no reason to use something else for this web application. Web2Executable is no longer maintained, but it works well with nw.js. Circuitjs1 is packaged in nw.js version 0.17.0. So far there is no sense to pack it into a later version of nw.js: this will only increase the size of the program.

If the program requires you to use the new version of nw.js then simply delete the "circuitjs1" folder located at C:\Users\ (your_username) \AppData\Local\

**Comment by SEVA77** [comment]
The next packaging tool will be nw-builder
