### ISSUE TITLE
Error during unpacking of linux-x64.zip, version 1.2.0

### ISSUE THREAD

**Issue by michaelsjackson** [SEVA77/circuitjs1#4]
While unpacking linux-x64.zip I am getting an error here, tried downloading again, same result. Will check now an older version.

**Comment by CEBA77** [comment]
I downloaded this archive. There are no errors...
![image](https://user-images.githubusercontent.com/32693567/65823747-0a117000-e265-11e9-9d1a-86a59ba18e90.png)

Perhaps it's the compression method. I thought LZMA is supported everywhere... For the previous version it was BZip2.

I will try to find a compression method suitable for releases. Refreshing these archives is not a problem. You can use 7-zip for this archive (p7zip for linux).

**Comment by michaelsjackson** [comment]
Sorry, I tried later again, it was ok.
